name: Validate HTML

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML
      uses: Cyb3r-Jak3/html5validator-action@v7.1.1
      with:
        root: .

    - name: Upload validation results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: validation-results.log
